version: '2'
services:
  web:
    build: .
    volumes:
      - .:/hardware
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    env_file: .env
    environment:
      HARDWARE_HOST: 0.0.0.0
      PG_HOST: postgres
      #PG_HOST: postgres
      #DATABASE_URL: postgres://hardwareDBuser:hardwareDBPassword@hardware_postgres:5432/hardwareDB

    links:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      PG_PASSWORD: postgres
      PG_USER: postgres